<a href="https://colab.research.google.com/github/Fozilkhoja/Fozilkhoja/blob/main/python_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

teen = pd.read_csv('Teen_Mental_Health_Dataset.csv')
teen.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [4]:
teen.shape

(1200, 13)

In [5]:
teen.index

RangeIndex(start=0, stop=1200, step=1)

In [6]:
teen.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='object')

In [7]:
teen.describe

<bound method NDFrame.describe of       age  gender  daily_social_media_hours platform_usage  sleep_hours  \
0      14    male                       7.9      Instagram          7.4
1      19  female                       1.9         TikTok          8.0
2      17  female                       1.3      Instagram          7.6
3      15    male                       7.4         TikTok          6.9
4      15  female                       4.7           Both          4.9
...   ...     ...                       ...            ...          ...
1195   18  female                       6.8      Instagram          6.6
1196   16    male                       2.3           Both          8.0
1197   14  female                       1.7           Both          8.7
1198   15    male                       3.9           Both          8.5
1199   16  female                       4.7         TikTok          6.5

      screen_time_before_sleep  academic_performance  physical_activity  \
0                          2.9                  3.01                1.5
1                          2.9                  3.22                0.8
2                          0.5                  3.92                0.0
3                          1.6                  3.48                0.8
4                          3.0                  2.37                1.4
...                        ...                   ...                ...
1195                       2.0                  2.76                1.0
1196                       1.9                  2.12                0.4
1197                       0.7                  3.98                0.8
1198                       2.1                  3.19                0.6
1199                       1.0                  2.91                0.9

     social_interaction_level  stress_level  anxiety_level  addiction_level  \
0                         low             2              2                1
1                        high             8              1               10
2                        high             2              4                2
3                      medium             1              7                9
4                      medium             3              5                2
...                       ...           ...            ...              ...
1195                      low             3              4                4
1196                     high             7              4                4
1197                     high             1              1                1
1198                     high             7              9                9
1199                   medium             5              7                3

      depression_label
0                    0
1                    0
2                    0
3                    0
4                    0
...                ...
1195                 0
1196                 0
1197                 0
1198                 0
1199                 0

[1200 rows x 13 columns]>

In [6]:
total = len(teen)
female = len(teen[teen['gender']=='female'])
male = len(teen[teen['gender']=='male'])

pct_f = (female/total)*100
pct_m = (male/total)*100

print(f"Yigitlar: {male} ta ({pct_m:.1f}%)")
print(f"Qizlar: {female} ta ({pct_f:.1f}%)")

Yigitlar: 615 ta (51.2%)
Qizlar: 585 ta (48.8%)

In [9]:
#O'smirlar eng ko'p qaysi platformadan (platform_usage) foydalanishadi? Har bir platformadan foydalanuvchilar soni

teen['platform_usage'].value_counts()

platform_usage
Instagram    411
TikTok       398
Both         391
Name: count, dtype: int64

In [23]:
#Uxlashdan oldin ekran vaqti 2 soatdan ko'p bo'lgan o'smirlarning necha foizi o'qishda (academic_performance) past ko'rsatkichga ega?
screen = teen[teen['screen_time_before_sleep'] > 2]
screen['screen_time_before_sleep'].value_counts()
pct = (screen['academic_performance'] < 3).mean()*100

print(f"Foizda: {pct:.2f}%")

Foizda: 50.68%

In [31]:
#depression_label ustunida 1 (bor) deb belgilangan o'smirlarning o'rtacha ijtimoiy tarmoqda o'tirish soati umumiy o'smirlarnikidan
#qanchalik farq qiladi?
dep = teen[teen['depression_label'] == 1]['daily_social_media_hours'].mean()
total_avg = teen['daily_social_media_hours'].mean()
dif = dep - total_avg

print(f"Depression_labeli 1 ga teng o'smirlar o'rtacha {dif} soatga ko'proq ijtimoiy tarmoqda o'tirishadi.")

Depression_labeli 1 ga teng o'smirlar o'rtacha 2.1826881720430116 soatga ko'proq ijtimoiy tarmoqda o'tirishadi.

In [38]:
#yangi sleep_quality (uyqu sifati) ustunini oching: agar sleep_hours 7 dan ko'p bo'lsa 'Yaxshi', 7 dan kam bo'lsa 'Yomon' deb qiymat bering.
teen['sleep_quality'] = np.where(teen['sleep_hours']>7, 'Yaxshi', 'Yomon')
teen.drop('quality', axis=1, inplace=True)
teen.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,sleep_quality
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0,Yaxshi
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,Yaxshi
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,Yaxshi
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0,Yomon
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0,Yomon

Har bir yosh bo'yicha o'smirlarning o'rtacha stress (stress_level), xavotir (anxiety_level) va o'qish ko'rsatkichini (academic_performance) hisoblang. Qaysi yoshda stress eng yuqori?

In [39]:
teen.groupby('age').agg({'stress_level': 'mean', 'anxiety_level': 'mean', 'academic_performance': 'mean'})

     stress_level  anxiety_level  academic_performance
age
13       5.460000       5.555000              3.013050
14       6.176471       5.333333              3.015229
15       5.133333       5.916667              3.012222
16       5.453988       5.644172              2.873988
17       5.170588       5.576471              3.017765
18       5.203488       5.418605              3.020698
19       5.623457       6.000000              2.970864

In [40]:
#Jins va platforma kesimida o'smirlarning o'rtacha ijtimoiy tarmoqda o'tkazadigan soatlarini hisoblang.
pivot = teen.pivot_table(
    columns='gender',
    index='platform_usage',
    values='daily_social_media_hours',
    aggfunc='mean')
pivot

gender            female      male
platform_usage
Both            4.547090  4.491584
Instagram       4.468473  4.648077
TikTok          4.526425  4.535610

In [41]:
#Ijtimoiy aloqa darajasi bo'yicha o'smirlarning o'rtacha telefonga qaramlik darajasini aniqlang.

teen.groupby('social_interaction_level')['addiction_level'].mean()

social_interaction_level
high      5.588076
low       5.467470
medium    5.641827
Name: addiction_level, dtype: float64

In [43]:
#Sonli ustunlar o'rtasidagi bog'liqlikni toping. Qaysi ikki omil bir-biriga eng kuchli bog'langan (musbat yoki manfiy)?
teen.corr(numeric_only=True)

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
age,1.000000,-0.006635,0.001530,0.075612,-0.013973,0.011086,-0.031208,0.026363,0.038265,0.010973
daily_social_media_hours,-0.006635,1.000000,-0.009472,0.035777,0.013179,0.025546,0.030698,0.027835,-0.024964,0.175201
sleep_hours,0.001530,-0.009472,1.000000,0.010235,0.021866,0.012701,-0.010979,-0.011879,-0.054838,-0.190630
screen_time_before_sleep,0.075612,0.035777,0.010235,1.000000,-0.034715,-0.026450,-0.008650,-0.010344,0.028884,-0.016502
academic_performance,-0.013973,0.013179,0.021866,-0.034715,1.000000,0.023312,-0.000600,-0.064379,0.029354,0.001441
physical_activity,0.011086,0.025546,0.012701,-0.026450,0.023312,1.000000,0.012159,-0.022233,0.026200,-0.017598
stress_level,-0.031208,0.030698,-0.010979,-0.008650,-0.000600,0.012159,1.000000,0.015811,-0.000129,0.170474
anxiety_level,0.026363,0.027835,-0.011879,-0.010344,-0.064379,-0.022233,0.015811,1.000000,0.031154,0.169566
addiction_level,0.038265,-0.024964,-0.054838,0.028884,0.029354,0.026200,-0.000129,0.031154,1.000000,-0.013952
depression_label,0.010973,0.175201,-0.190630,-0.016502,0.001441,-0.017598,0.170474,0.169566,-0.013952,1.000000

In [52]:
#"Jismoniy faollik stressni kamaytiradi" degan fikr to'g'rimi?
#Sport bilan haftasiga 1 soatdan ko'p shug'ullanadiganlar va umuman shug'ullanmaydiganlarning o'rtacha stress darajasini solishtiring.

no_sport = teen[teen['physical_activity']==0]
stress = no_sport['stress_level'].mean()

sport = teen[teen['physical_activity']>1]
stress_s = sport['stress_level'].mean()

print(f"Sport bilan shug'ullanmaydiganlarning o'rtacha stress darajasi: {stress}")
print(f"Sport bilan shug'ullanadiganlarning o'rtacha stress darajasi: {stress_s}")

Sport bilan shug'ullanmaydiganlarning o'rtacha stress darajasi: 5.088235294117647
Sport bilan shug'ullanadiganlarning o'rtacha stress darajasi: 5.444444444444445